language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      addons:
        apt:
          packages:
            - tree
            - libuv-dev
    - os: osx
      osx_image: xcode7.3

install:
  - 'if [[ "${TRAVIS_OS_NAME}" == "osx" ]] ; then brew update && brew install --force openssl libuv tree ; fi'

script:
  - 'set -e'
  - 'export PREFIX="/tmp/install"'
  - 'export MAKEFLAGS="-j8"'

  - 'make'

  - 'make install'
  - 'tree "${PREFIX}"'

  - 'make tests'
  - 'time $([[ "${TRAVIS_OS_NAME}" == "linux" ]] && echo "catchsegv") ./testsBin'

notifications:
    email: false
